language: nix
env:
  - NIXPKGS_CHANNEL=17.09
  - NIXPKGS_CHANNEL=unstable

# By building the tests, we also build yarn2nix itself.
script: nix-build -I "nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-$NIXPKGS_CHANNEL.tar.gz" tests.nix
